### ISSUE TITLE
Cannot submit transaction generated by StdSignMsg but CreateAndSignTx works fine

### ISSUE THREAD

**Issue by codemaster101** [terra-project/terra.js#45]
Hi, 
I was trying to implement Terra for an offline wallet.
I used the following code to generate a signed transaction object:

```
  public async signOfflineTransaction(
    toAddress: string,
    ticker: string,
    value: number,
    gas: number,
    sequenceNumber: number,
    accountNumber: number,
    memo?: string,
  ): Promise<StdTx> {
    const amount = {
      uluna: 10000,
    };

    const send = new MsgSend(
      'terra13qz3dqq9g5wpqqkf7ca5yxk3jsgz94a4rrrpak',
      'terra17ymz26ky4jfzmw6uedu0g397hljr70a7k9ne4v',
      amount,
    );

    const fee = new StdFee(1000, { uluna: 10000 });

    const unsignedTx = new StdSignMsg(
      'tequila-0004',
      10,
      1720,
      fee,
      [send],
      memo,
    );

    const signedTx = await this.wallet.key.signTx(unsignedTx);
    return signedTx;
  }
```

When I run this program I get the following result:
**SIGNED OBJECT A**
```
{
  "type": "core/StdTx",
  "value": {
    "fee": {
      "amount": [
        {
          "amount": "10000",
          "denom": "uluna"
        }
      ],
      "gas": "1000"
    },
    "memo": "",
    "msg": [
      {
        "type": "bank/MsgSend",
        "value": {
          "amount": [
            {
              "amount": "10000",
              "denom": "uluna"
            }
          ],
          "from_address": "terra13qz3dqq9g5wpqqkf7ca5yxk3jsgz94a4rrrpak",
          "to_address": "terra17ymz26ky4jfzmw6uedu0g397hljr70a7k9ne4v"
        }
      }
    ],
    "signatures": [
      {
        "pub_key": {
          "type": "tendermint/PubKeySecp256k1",
          "value": "AxkYYhGJ5JoGd+GXzSCkdiur4/CCFJ26UluiQxshxve3"
        },
        "signature": "2foLuO919vLrOTMzCImWM10HylFPJg4XeLB+6jextXduUyWy6ATuRfM6gb9rf0ssHQZCxXYYcNJ9quJrWEUt9g=="
      }
    ]
  }
}
```
This looks fine, as I generated another transaction with the exact same wallet, but this time with CreateAndSignTx (cannot use this as it requires a call for sequence number and account number which is not possible for my offline wallet).
The CreateAndSignTx looks something like this:
(**SIGNED OBJECT B**)
```
{
  "type": "core/StdTx",
  "value": {
    "fee": {
      "amount": [
        {
          "amount": "91418000",
          "denom": "uluna"
        }
      ],
      "gas": "91418"
    },
    "memo": "",
    "msg": [
      {
        "type": "bank/MsgSend",
        "value": {
          "amount": [
            {
              "amount": "10000",
              "denom": "uluna"
            }
          ],
          "from_address": "terra13qz3dqq9g5wpqqkf7ca5yxk3jsgz94a4rrrpak",
          "to_address": "terra17ymz26ky4jfzmw6uedu0g397hljr70a7k9ne4v"
        }
      }
    ],
    "signatures": [
      {
        "pub_key": {
          "type": "tendermint/PubKeySecp256k1",
          "value": "AxkYYhGJ5JoGd+GXzSCkdiur4/CCFJ26UluiQxshxve3"
        },
        "signature": "lhy7nSlV9jJ+kCdxu/CA5Zcf+R+9sHMIpEkwy4ZH5Q8Vlu1boRbgObcR+cw3RO80rpiGNM77C0FAcPlJW9Z+3g=="
      }
    ]
  }
}
```
Submitting this **signed object B** was a success: `005F5DC78379EA293F6A687117699F896070D735B82F38A2AFC5C0422254E1ED` you can verify it on the explorer.

But whenever I try to submit **signed object A**, I get an error like:
```
{ height: 0,
  txhash:
   'BAC34EEA8472591F787E69DCC9A082BCDECFDDAD602B05DE714951BB7D4BBD0D',
  raw_log:
   'out of gas: out of gas in location: ReadPerByte; gasWanted: 1000, gasUsed: 1054',
  gas_wanted: 1000,
  gas_used: 1054,
  code: 11,
  codespace: 'sdk' }
```
I tried increasing the gas, but then it requires even more gas. For example if I write, 6000 it will give me an error like:
```
{ height: 0,
  txhash:
   '1C07F3AD2FB532ABDAB12767D13E61630E1DDBBBC07F3FCF3BCD015FA22083A8',
  raw_log:
   'out of gas: out of gas in location: ReadFlat; gasWanted: 6000, gasUsed: 6111',
  gas_wanted: 6000,
  gas_used: 6111,
  code: 11,
  codespace: 'sdk' }
```
and so on and so forth (3000 gas requires -> 3069).
Not completely sure why this is not working, given I tried to follow what is there in the documentations. 
If there is something missing, is there a way to implement Terra for offline wallets? Do I need to make some changes in how I am feeding data into StdSignMsg (since I see the gas and value being sent is different to CreateAndSignTx method).

**Comment by codemaster101** [comment]
An example for implementation for cold/offline wallets would also be helpful.

**Comment by YunSuk-Yeo** [comment]
@codemaster101 You are doing good way for offline tx singing.
Depends on the tx you want to broadcast, you should use different static gas.

Ex) MsgSend takes almost 75000 gas per each.

The reason, it keeps saying "out of gas; you need a bit more gas", is the node stops simulation when the specified gas is ran out. When you want to find proper gas for that msg, increase gas in 10000 unit.

**Comment by codemaster101** [comment]
Ok it seems that the gas you provide, @YunSuk-Yeo , should be less than equal to the amount you want to transfer, if so why is that? As I tried doing 1000/10000 as the amount I want to transfer and it runs out of money. But when I provide the transaction amount to be 1,000,000 uluna -> 1 LUNA and gas to be 80,000 (out of which 66 thousand was used), the transaction fee eventually came out to be 1 LUNA as well. My question would be:  If the amount I am transferring gets transferred as a whole and fee is deducted separately, why would the node give me this error: ->
```
{ height: 0,
  txhash:
   'F229A381E20BDF46D2242BDFDB41FD6AFFFB886B208C6656C772F907406321DD',
  raw_log:
   'insufficient fee: insufficient fees; got: "10000uluna", required: "13353750ukrw,11250uluna,32371943umnt,7635usdr,11250uusd" = "13353750ukrw,11250uluna,32371943umnt,7635usdr,11250uusd"(gas) +""(stability)',
  gas_wanted: 75000,
  gas_used: 1054,
  code: 13,
  codespace: 'sdk' }
```

Also, you were right. I provided around 80000 and the transaction succeeded https://finder.terra.money/tequila-0004/tx/A422CD657F8BD73E6DF75525833F133AB608C24D2F14DDFABD228483CB22B944.

**Comment by codemaster101** [comment]
Also is there any way to get `gas` from the node for specific type of transactions?
Like MsgSend, MsgVote etc.

**Comment by codemaster101** [comment]
Need to run a dummy transaction with a fake fee and then call estimate fee function to estimate the fee for that transaction.
Like so:
```
    if (gas === undefined && amount === undefined) {
      fee = new StdFee(0, { [ticker]: 1 });
    } else {
      // @ts-ignore
      fee = new StdFee(gas, { [ticker]: feeAmount });
    }

    const unsignedTx = new StdSignMsg(
      this.chainId,
      sequenceNumber,
      accountNumber,
      fee,
      [messageObject],
      memo || '',
    );

.
.
.
 public async getFee(transaction: StdSignMsg | StdTx) {
    return this.terraClient.tx.estimateFee(transaction);
  }
```
Hope it helps!
