### ISSUE TITLE
How I can get max spendable amount?

### ISSUE THREAD

**Issue by rizhenkov** [terra-project/terra.js#64]
Hi! Please, give me an example, how can I ask LCD to return:
1. Max spendable amount uluna
2. Generate tx with max spendable amount with a normal fee size

Or **how I can calculate it** from balance with all available public data (as treasuryTaxRate)? 

I tried to found this on Station sources but unsuccessfully🥺

**Comment by hanjukim** [comment]
It depends on transaction details. Frankly, it is not simple as it looks. @simcheolhwan could you please explain this to us?

**Comment by rizhenkov** [comment]
> It depends on transaction details. 

Of course, I about sending luna from one address to another.

(Of course, it will be good to read too about what changes in formulas when we send stable tokens)

**Comment by amanusk** [comment]
@rizhenkov you can check out this code as reference
https://github.com/ZenGo-X/terra-thresh-wallet/blob/9b94f218a1333006fd7ddf39a92413846b4a7d48/src/client.ts#L122

**Comment by simcheolhwan** [comment]
> It depends on transaction details. Frankly, it is not simple as it looks. @simcheolhwan could you please explain this to us?

If user pay gas fee with another denom:

```
calculated_tax = ceil(balance * tax_rate / (1 + tax_rate))
tax = min(calculated_tax, tax_cap)
max = balance - tax
```

**Comment by rizhenkov** [comment]
@amanusk Yes, by the your code, a real transaction is created first via LCD, and then the fee amount is subtracted from the balance.
I also thought about this solution, I was worried that this might is a kludge and maybe exists the more elegant solution.

**Comment by amanusk** [comment]
@rizhenkov, you are right.
There needs to be a way to estimate the fee before sending.
If your balance is 100 LUNA, and you estimate fee with exactly 100 LUNA, you'll get a wrong fee estimation and the Tx will fail.
One approach is to hard code some high enough value to always use the same amount of gas.
I don't prefer this approach. Instead, to account for both fee and tax, I first estimate the gas of a successful send, and if a "sendAll" is required I readjust the final tx with both gas fees and tax.
Link here if you have a better idea :)

**Comment by rizhenkov** [comment]
There are no better ideas at that moment)
