### ISSUE TITLE
testnet lcd api SSL cert expired

### ISSUE THREAD

**Issue by calvinkei** [terra-project/terra.js#75]
getting this error trying to connect to testnet
`net::ERR_CERT_DATE_INVALID`
try going to https://soju-lcd.terra.dev/ and the cert is expired

**Comment by hanjukim** [comment]
soju-lcd.terra.dev is retired.

**Comment by calvinkei** [comment]
@hanjukim thanks. what will be the chain id? is it documented somewhere?
